[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "3.2.4"
  NODE_VERSION = "18"

[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [
    "node_modules/.cache/webpack",
  ]
