---
name: Maintenance task / chore
about: Report a maintenance task
title: [chore] [description]
labels: repo, help wanted, chore
assignees: ''
body:
- type: markdown
  attributes:
    value: |
      Tell us about this chore.
- type: textarea
  id: chore
  attributes:
    label: What do we need to do?
  validations:
    required: true
