name: "Documentation Migration request"
description: "Document the migration of documentation from the legacy site to the new one"
title: "[docs] Migrate [Old doc title] to [New docs title]"
labels: documentation, migration
body:
- type: markdown
  attributes:
    value: |
      Thank you for suggesting a migration. Please give us a bit more detail about which path needs to be moved.
- type: input
  id: oldUrl
  attributes:
    label: The URL of the page on https://docs.moodle.org/dev/
    placeholder: https://docs.moodle.org/dev/...
  validations:
    required: true
- type: dropdown
  id: isVersioned
  attributes:
    label: Is this documentation specific to a Moodle version?
    options:
      - "Unsure (Default)"
      - "Yes"
      - "No"
- type: textarea
  id: newLocation
  attributes:
    label: What location would you suggest in the new docs?
    description: What location do you think makes sense most?
