name: "System bug or error"
description: "Report a problem with the documentation system, the Docusaurus Framework, scripting, and similar areas."
title: "[repo] Problem with documentation system"
labels: repo, help wanted, bug
body:
- type: markdown
  attributes:
    value: |
      Thank you for your bug report. Please give us a bit more detail about the issue so that we can look into it.
- type: textarea
  id: problem
  attributes:
    label: What is the issue that you're experiencing?
  validations:
    required: true
- type: dropdown
  id: canHelp
  attributes:
    label: Are you able to provide a patch for this?
    options:
      - No (Default)
      - Yes - I have one prepared
      - Yes - I will create one

