name: Push the list of migrated pages to Wikimedia

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        description: 'Set the debug mode'

jobs:
  run:
    name: Push migated pages to Wikimedia
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run update script
        run: yarn wikimedia-sync push-migrated
        env:
          DEBUG: ${{ github.event.inputs.debug }}
          WIKIMEDIA_DEBUG: ${{ github.event.inputs.debug }}
          WIKIMEDIA_SECRET: ${{ secrets.WIKIMEDIA_PASSWORD }}
          WIKIMEDIA_USER: ${{ secrets.WIKIMEDIA_USER }}
